### ISSUE TITLE
[wgsl-in] Variable with same name as function

### ISSUE THREAD

**Issue by munrocket** [gfx-rs/naga#1046]
Shadowing is not supported.

Uncomment lines to get an error in minimal example.
https://codepen.io/munrocket/pen/bGWGZwM

**Comment by kmdreko** [comment]
Tacking on another example.

A StackOverflow user used code samples directly from the W3 WGSL docs and ran into errors.

```
struct VertexInput {
    [[location(0)]] pos: vec3<f32>;
};

struct VertexOutput {
    [[builtin(position)]] pos: vec4<f32>;
};

[[stage(vertex)]]
fn main(vertex_input: VertexInput) -> VertexOutput {
    var out: VertexOutput;
    out.pos = vec4<f32>(vertex_input.pos, 1.0);

    var a: i32 = 2;
    var i: i32 = 0;
    loop {
        if (i >= 4) { break; }
    
        let step: i32 = 1;
    
        i = i + step;
        if (i % 2 == 0) { continue; }
    
        a = a * 2;
    }

    return out;
}

[[stage(fragment)]]
fn main(in: VertexOutput) -> [[location(0)]] vec4<f32> {
    return vec4<f32>(1.0, 1.0, 1.0, 1.0);
}
```

```
[2021-08-18T16:13:33Z ERROR wgpu_core::device] Failed to parse WGSL code for Some("Shader: simple shader"): expected '(', found ';'
[2021-08-18T16:13:33Z ERROR wgpu::backend::direct] wgpu error: Validation Error

    Caused by:
        In Device::create_shader_module
          note: label = `Shader: simple shader`
        Failed to parse WGSL
```

The error being caused by the `i = i + step` line. Apparently the `step` identifier is still expecting the built-in `step()` function.

[Original post](https://stackoverflow.com/questions/68833291/wgpu-correctly-written-wgsl-shader-parsing-error).

**Comment by kvark** [comment]
This was fixed by #1204

**Comment by munrocket** [comment]
In this [example](https://codepen.io/munrocket/pen/bGWGZwM ) function with name “qrotor” cusses error because another one have an argument with same name. Looks like #1204 fixes only built-in names.

**Comment by munrocket** [comment]
Variable with same name as function still not work. I am updated example for current Firefox Nightly.
https://codepen.io/munrocket/pen/bGWGZwM

**Comment by kvark** [comment]
Current Nightly doesn't have the latest Naga. It's going to be a big update, but it's blocked currently on https://github.com/rust-lang/cargo/issues/9856
