### ISSUE TITLE
[glsl-in] Unknown function 'texelFetch'

### ISSUE THREAD

**Issue by fintelia** [gfx-rs/naga#1231]
The GLSL frontend seems to be missing support for the texelFetch function. 

_**Edit**: ...when used with a 2D array texture._ 
```glsl
#version 450 core
#extension GL_EXT_samplerless_texture_functions: require

layout(set = 0, binding = 0) uniform texture2DArray normals;

void main() {
    vec4 v = texelFetch(normals, ivec3(0), 0);
}
```
```
error: Unknown function 'texelFetch'
  ┌─ texel.frag:8:14
  │
8 │     vec4 v = texelFetch(normals, ivec3(0), 0);
  │              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by JCapucho** [comment]
The function should be implemented can you share the shader you are trying or the types used in the call?

**Comment by fintelia** [comment]
Seems that the problem is that I'm trying to pass a texture2DArray. It works just fine if I specify a texture3D for the first argument instead

**Comment by fintelia** [comment]
I'm seeing a similar issue with `sampler2DArray(...)`:
```glsl
#version 450 core

layout(set = 0, binding = 0) uniform sampler linear;
layout(set = 0, binding = 1) uniform texture2DArray normals;

void main() {
    vec4 v = texture(sampler2DArray(normals, linear), vec3(0));
}
```
```
error: Unknown function 'sampler2DArray'
  ┌─ sampler.frag:7:22
  │
7 │     vec4 v = texture(sampler2DArray(normals, linear), vec3(0));
  │                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

(I can open a separate issue for this if you'd like, but it seems like they may have the same root cause)

**Comment by magcius** [comment]
This should be fixed now that sampler2DArray is working.

**Comment by fintelia** [comment]
@magcius I just checked against a9d20d8ef4a03bf60402dec806b9949a733f11a7. The original code sample still fails, although the version with `texture(...)` works now.
